PROD = False
LOCATION = "queenstown"
NOTIFICATION_LIST = ["someone@gmail.com","someoneelse@gmail.com"]
DATABASE = "db"
USER = "user"
HOST= "localhost"
PASSWD = "password"
HOME = "/home/pi/PiRainMaker/"
SOIL_STRESS_POINT = 40      #Permanent Wilting Point + 10
SOIL_AT_RISK_LEVEL1 = 45         
SOIL_AT_RISK_LEVEL2 = 50
RAIN_FORECAST_12HRS_MIN = 5.0
RAIN_FORECAST_48HRS_MIN = 5.0
WATERING_TIME = 10